default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  encoding: unicode
  database: dev_db
  username: postgres
test:
  <<: *default
  encoding: unicode
  database: test_db
  username: postgres

production:
  <<: *default
